server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<path>.*), /$\{path}


management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  instance:
    hostname: cloudgateway
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka 