server:
  port: 5001

spring:
  application:
    name: INVENTORY-SERVICE
  datasource:
    url: jdbc:mysql://mysql-inventory:3306/inventory
    username: muratcan
    password: yeldan
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost
    ip-address: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://eureka:8761}/eureka